### ISSUE TITLE
Would you be willing to add a license?

### ISSUE THREAD

**Issue by tjdevries** [dreadatour/RPMSpec#6]
Hi!

I'd like to add rpm spec highlighting to this repo: https://github.com/slimsag/Packages but to do so I would need a license from this project. Would it be possible to add a permissive license so that we could use it?

Thanks for your consideration!

**Comment by dreadatour** [comment]
Hi!
Sure! Can I have your advice on which licence should I pick and how to add it to the repo?
Thank you!

**Comment by dreadatour** [comment]
Done! Thank you!

**Comment by tjdevries** [comment]
Thank you very much! Hope you have a great day :)
